### ISSUE TITLE
Align filter options with the products (see picture)

### ISSUE THREAD

**Issue by ianfader** [CCI-Studios/Hey-Babies#18]
![screen shot 2015-08-24 at 10 15 40 am](https://cloud.githubusercontent.com/assets/8989188/9442340/711230ae-4a49-11e5-9033-e6b3a3be3c6c.jpg)

**Comment by ccmorris** [comment]
Can you describe what you mean in more detail please?

**Comment by ccmorris** [comment]
Note to self: center the filter options

**Comment by ccmorris** [comment]
![screen shot 2015-09-03 at 9 09 10 am](https://cloud.githubusercontent.com/assets/4417748/9659018/a0241694-521b-11e5-9a72-fc91d525a3bc.png)
Does this look odd to you?

**Comment by ccmorris** [comment]
Note to self: center all the things
