### ISSUE TITLE
Sign in/signup before proceeding to checking out

### ISSUE THREAD

**Issue by ianfader** [CCI-Studios/Hey-Babies#20]
Should we ask the user if they are already an existing user, new customer, or continue as guest before checking out? Or is this step unnecessary?

**Comment by ccmorris** [comment]
I know we talked about this, and I cannot recall what we decided to do here.

**Comment by ccmorris** [comment]
Make there 2 buttons on the 'my bag' page: sign in & checkout, guest checkout
