### ISSUE TITLE
Product Details - Quantity amount field

### ISSUE THREAD

**Issue by ianfader** [CCI-Studios/Hey-Babies#24]
For items that have more than one in stock. Dropdown with the max number that is available or show the amount we have in stock and users will have to type in the amount they want.

**Comment by ccmorris** [comment]
Let's talk about this. I would prefer not having this on the product detail page.

**Comment by ccmorris** [comment]
After discussion, we will not add a quantity field to the product detail page, since it will be on the next page when you "add to bag", and most products will only have 1 quantity available anyways.
